<?php

/*
 * Copyright Matthew Asham and BinktermPHP Contributors
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
 * following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE
 */

namespace BinktermPHP\AreaFix;

/**
 * Structural parser for AreaFix and FileFix response messages from FTN hub mailers.
 *
 * Recognizes concrete syntactic structures generated by major hub software:
 * - Mystic BBS & MBSE Command/Result blocks (direct actions, stacked requests, indented lists)
 * - Delimited tables (Husky, Clearing Houz, FastEcho, FrontDoor, InterMail)
 * - Columnar and dotted-leader tables (HPT, Husky)
 *
 * By relying on structural grammar rather than keyword blocklisting, real areas
 * with common names (such as LINUX, BASE, WINDOWS) are preserved, while help
 * manuals and freeform prose are never misidentified as area lists.
 */
class AreaFixParser
{
    public const ACTION_SUBSCRIBE = 'subscribe';
    public const ACTION_UNSUBSCRIBE = 'unsubscribe';
    public const ACTION_AVAILABLE = 'available';

    /**
     * Parse AreaFix or FileFix response body into structured area items.
     *
     * @param string $body Raw message body text
     * @param string|null $subject Optional message subject for context
     * @return array<int, array{
     *     name: string,
     *     description: ?string,
     *     action: string,
     *     is_subscribed: bool
     * }>
     */
    public function parse(string $body, ?string $subject = null): array
    {
        $body = str_replace(["\r\n", "\r"], "\n", $body);

        // 1. Try Mystic BBS / MBSE Command & Result block format
        $mysticAreas = $this->parseMysticBlocks($body);
        if ($mysticAreas !== null && !empty($mysticAreas)) {
            return $this->deduplicateAreas($mysticAreas);
        }

        // 2. Try delimited table format (: or |)
        $delimitedAreas = $this->parseDelimitedTable($body);
        if ($delimitedAreas !== null && !empty($delimitedAreas)) {
            return $this->deduplicateAreas($delimitedAreas);
        }

        // 3. Try columnar / dotted-leader table format (HPT / Husky)
        $columnarAreas = $this->parseColumnarTable($body);
        if ($columnarAreas !== null && !empty($columnarAreas)) {
            return $this->deduplicateAreas($columnarAreas);
        }

        return [];
    }

    /**
     * Check whether message body contains actionable AreaFix area data
     * (subscriptions, unsubscriptions, or valid area lists).
     *
     * Returns false for help manuals, empty rescan receipts, and error notifications.
     */
    public function hasActionableContent(string $body, ?string $subject = null): bool
    {
        $areas = $this->parse($body, $subject);
        return !empty($areas);
    }

    /**
     * Parse Mystic BBS and MBSE Command / Result blocks.
     *
     * Matches patterns:
     *   Command: +TAG [R=100]
     *    Result: Echo will now be exported
     *
     *   Command: -TAG
     *    Result: Echo will no longer be exported
     *
     *   Command: %LINKED (or %QUERY, %LIST, %UNLINKED)
     *    Result: List of all linked areas:
     *     TAG1                                Description 1
     *     TAG2                                Description 2
     *
     * @return array<int, array{name: string, description: ?string, action: string, is_subscribed: bool}>|null
     */
    private function parseMysticBlocks(string $body): ?array
    {
        if (!preg_match('/^Command:\s*/m', $body)) {
            return null;
        }

        $lines = explode("\n", $body);
        $areas = [];
        $totalLines = count($lines);

        for ($i = 0; $i < $totalLines; $i++) {
            $line = $lines[$i];

            // Stop command parsing once a help manual banner is reached
            if (preg_match('/^[\.\+\s]*-{3,}.*Help/i', $line) || preg_match('/^\|\s*.*(?:AreaFix|FileFix)\s+Help\s*\|/i', $line)) {
                break;
            }

            // Real Mystic command lines start flush at column 0 (not indented inside tutorial examples)
            if (!preg_match('/^Command:\s*(.+)$/i', $line, $cmdMatch)) {
                continue;
            }

            $commandRaw = trim($cmdMatch[1]);

            // Find subsequent Result: line (within next 3 lines)
            $resultRaw = null;
            $resultLineIndex = -1;
            for ($j = $i + 1; $j < min($i + 4, $totalLines); $j++) {
                if (preg_match('/^Result:\s*(.*)$/i', trim($lines[$j]), $resMatch)) {
                    $resultRaw = trim($resMatch[1]);
                    $resultLineIndex = $j;
                    break;
                }
            }

            if ($resultRaw === null) {
                continue;
            }

            // A) Direct subscription command: +TAG [params]
            if (preg_match('/^\+\s*([A-Za-z0-9_\-\.]+)(?:\s+\[[^\]]*\])?$/', $commandRaw, $tagMatch)) {
                $tag = strtoupper($tagMatch[1]);
                if (self::isValidTag($tag)) {
                    // Check if result indicates success
                    if (preg_match('/(?:will now be exported|linked|added|subscribed|now connected|echo linked)/i', $resultRaw)) {
                        $areas[] = [
                            'name'          => $tag,
                            'description'   => null,
                            'action'        => self::ACTION_SUBSCRIBE,
                            'is_subscribed' => true,
                        ];
                    }
                }
                $i = $resultLineIndex;
                continue;
            }

            // B) Direct unsubscription command: -TAG [params]
            if (preg_match('/^\-\s*([A-Za-z0-9_\-\.]+)(?:\s+\[[^\]]*\])?$/', $commandRaw, $tagMatch)) {
                $tag = strtoupper($tagMatch[1]);
                if (self::isValidTag($tag)) {
                    if (preg_match('/(?:will no longer be exported|unlinked|removed|unsubscribed|disconnected)/i', $resultRaw)) {
                        $areas[] = [
                            'name'          => $tag,
                            'description'   => null,
                            'action'        => self::ACTION_UNSUBSCRIBE,
                            'is_subscribed' => false,
                        ];
                    }
                }
                $i = $resultLineIndex;
                continue;
            }

            // C) List commands: %LINKED, %QUERY, %LIST, %UNLINKED, %AVAIL
            if (preg_match('/^%([A-Za-z0-9_\-]+)\b/i', $commandRaw, $pctMatch)) {
                $cmdName = strtoupper($pctMatch[1]);
                $isLinkedCmd   = in_array($cmdName, ['LINKED', 'QUERY', 'LINK'], true);
                $isUnlinkedCmd = in_array($cmdName, ['UNLINKED'], true);
                $isListCmd     = in_array($cmdName, ['LIST', 'AVAIL'], true);

                if (($isLinkedCmd || $isUnlinkedCmd || $isListCmd) && preg_match('/list of/i', $resultRaw)) {
                    // Indented lines immediately follow the Result: line
                    $k = $resultLineIndex + 1;
                    while ($k < $totalLines) {
                        $dataLine = $lines[$k];
                        $dataTrim = trim($dataLine);

                        // Stop if we hit a new command or a non-indented decorative section
                        if (preg_match('/^Command:\s*/i', $dataTrim) || preg_match('/^[.\-+=\*]{3,}/', $dataTrim)) {
                            break;
                        }

                        // An indented data row starts with 2+ spaces or a tab
                        if (preg_match('/^(?:[ ]{2,}|\t+)([A-Za-z0-9_\-\.]+)(?:\s{2,}|\t+)(.*)$/', $dataLine, $rowMatch)) {
                            $tag = strtoupper(trim($rowMatch[1]));
                            $desc = trim($rowMatch[2]);
                            if (self::isValidTag($tag)) {
                                $action = $isLinkedCmd ? self::ACTION_SUBSCRIBE : self::ACTION_AVAILABLE;
                                $areas[] = [
                                    'name'          => $tag,
                                    'description'   => $desc !== '' ? $desc : null,
                                    'action'        => $action,
                                    'is_subscribed' => $isLinkedCmd,
                                ];
                            }
                        } elseif ($dataTrim !== '' && !preg_match('/^[ ]{2,}|\t+/', $dataLine)) {
                            // Non-indented non-empty line ends the listing block
                            break;
                        }

                        $k++;
                    }
                    $i = $k - 1;
                    continue;
                }
            }

            // Advance past the result line
            $i = $resultLineIndex;
        }

        return $areas;
    }

    /**
     * Parse delimited tables (colon ':' or pipe '|').
     *
     * Matches patterns:
     *   :---:------------:--------------------------------------------------:------:
     *   :   : AREA       : DESCRIPTION                                      : MSGS :
     *   :---:------------:--------------------------------------------------:------:
     *   :*  : FSX_ADS    : FSX: Ads + ANSI Art                              :  547 :
     *   :   : FSX_BBS    : FSX: BBS Support/Dev                             :   53 :
     *
     * Or pipe tables:
     *   | AREA | DESCRIPTION |
     *   | FSX_ADS | FSX: Ads + ANSI Art |
     *
     * @return array<int, array{name: string, description: ?string, action: string, is_subscribed: bool}>|null
     */
    private function parseDelimitedTable(string $body): ?array
    {
        $lines = explode("\n", $body);
        $headerFound = false;
        $delimiter = null;
        $tagCol = -1;
        $descCol = -1;
        $statusCol = -1;
        $areas = [];

        $totalLines = count($lines);

        for ($i = 0; $i < $totalLines; $i++) {
            $line = trim($lines[$i]);
            if ($line === '') {
                if ($headerFound && !empty($areas)) {
                    // Blank line after table rows concludes the table
                    break;
                }
                continue;
            }

            // Look for table header if not found yet
            if (!$headerFound) {
                // Must contain AREA/ECHOTAG and DESCRIPTION/STATUS/MSGS/FILES
                if (preg_match('/[:|]\s*(?:AREA|ECHOTAG|TAG)\s*[:|]/i', $line)) {
                    $delimiter = str_contains($line, ':') ? ':' : '|';
                    $cols = array_map('trim', explode($delimiter, $line));

                    // Remove empty outside elements from boundary delimiters
                    if (isset($cols[0]) && $cols[0] === '') {
                        array_shift($cols);
                    }
                    if (!empty($cols) && end($cols) === '') {
                        array_pop($cols);
                    }

                    foreach ($cols as $idx => $colName) {
                        $colUpper = strtoupper($colName);
                        if (in_array($colUpper, ['AREA', 'ECHOTAG', 'TAG'], true)) {
                            $tagCol = $idx;
                        } elseif (in_array($colUpper, ['DESCRIPTION', 'DESC'], true)) {
                            $descCol = $idx;
                        } elseif ($idx === 0 && ($colUpper === '' || in_array($colUpper, ['STATUS', 'ST', 'FLAGS'], true))) {
                            $statusCol = $idx;
                        }
                    }

                    if ($tagCol >= 0) {
                        $headerFound = true;
                    }
                }
                continue;
            }

            // Once header is found, parse table rows
            // Skip decorative separator lines (:---:---:, |---|---|)
            if (preg_match('/^[:|\s]*[-=*#~:\s]{3,}[:|\s]*$/', $line)) {
                continue;
            }

            // Data line must start with or contain the delimiter
            if (!str_contains($line, $delimiter)) {
                if (!empty($areas)) {
                    break; // End of table
                }
                continue;
            }

            $rawCols = explode($delimiter, $line);
            if (isset($rawCols[0]) && trim($rawCols[0]) === '') {
                array_shift($rawCols);
            }
            if (!empty($rawCols) && trim(end($rawCols)) === '') {
                array_pop($rawCols);
            }

            if (isset($rawCols[$tagCol])) {
                $tag = strtoupper(trim($rawCols[$tagCol]));
                if (self::isValidTag($tag)) {
                    $desc = null;
                    if ($descCol >= 0 && isset($rawCols[$descCol])) {
                        $hasTrailingCol = count($cols) > ($descCol + 1);
                        if ($hasTrailingCol && count($rawCols) > ($descCol + 1)) {
                            $numTrailing = count($cols) - 1 - $descCol;
                            $sliceLen = max(1, count($rawCols) - $descCol - $numTrailing);
                            $descParts = array_slice($rawCols, $descCol, $sliceLen);
                            $desc = trim(implode($delimiter, $descParts));
                        } else {
                            $descParts = array_slice($rawCols, $descCol);
                            $desc = trim(implode($delimiter, $descParts));
                        }
                    }

                    // Discard description if it contains ANSI box drawing / block art
                    if ($desc !== null && (preg_match('/[▄█▀▌▐░▒▓─│┌┐└┘├┤┬┴┼═║]/u', $desc) || preg_match('/[\xB0-\xDF]/', $desc))) {
                        $desc = null;
                    }

                    $status = ($statusCol >= 0 && isset($rawCols[$statusCol])) ? trim($rawCols[$statusCol]) : '';

                    $isSubscribed = str_contains($status, '*') || str_contains($status, '+');
                    $action = $isSubscribed ? self::ACTION_SUBSCRIBE : self::ACTION_AVAILABLE;

                    $areas[] = [
                        'name'          => $tag,
                        'description'   => ($desc !== null && $desc !== '') ? $desc : null,
                        'action'        => $action,
                        'is_subscribed' => $isSubscribed,
                    ];
                }
            }
        }

        return $headerFound ? $areas : null;
    }

    /**
     * Parse columnar fixed-width or dotted-leader tables (HPT, Husky, FastEcho).
     *
     * Matches patterns:
     *   Area                                                Status
     *   --------------------------------------------------  -------------------------
     *   LVLY_ANNOUNCE ....................................  rescanned 22 mails
     *   LVLY_BINKTERMPHP .................................  subscribed
     *
     * Or:
     *   Area                                                Description
     *   --------------------------------------------------  -------------------------
     *   SYS_GEN                                             SysOp General Chat
     *
     * @return array<int, array{name: string, description: ?string, action: string, is_subscribed: bool}>|null
     */
    private function parseColumnarTable(string $body): ?array
    {
        $lines = explode("\n", $body);
        $headerFound = false;
        $isStatusTable = false;
        $areas = [];

        $totalLines = count($lines);

        for ($i = 0; $i < $totalLines; $i++) {
            $line = trim($lines[$i]);

            if (!$headerFound) {
                // Look for "Area" column followed by "Status" or "Description"
                if (preg_match('/^Area\s{3,}(Status|Description|Msgs|Files)\b/i', $line, $hMatch)) {
                    // Check if next line is a dash separator
                    if (isset($lines[$i + 1]) && preg_match('/^[-=]{3,}\s+[-=]{3,}/', trim($lines[$i + 1]))) {
                        $headerFound = true;
                        $isStatusTable = (strcasecmp($hMatch[1], 'Status') === 0);
                        $i++; // skip separator line
                        continue;
                    }
                }
                continue;
            }

            // End of table boundaries
            if ($line === '' || str_starts_with($line, '---') || str_starts_with($line, '* Origin:') || str_contains($line, 'Following is the original message text')) {
                if (!empty($areas)) {
                    break;
                }
                continue;
            }

            // Parse dotted-leader line: TAG ........ Status or Description
            if (preg_match('/^([A-Za-z0-9_\-\.]+)\s+\.{3,}\s*(.*)$/', $line, $rowMatch)) {
                $tag = strtoupper(trim($rowMatch[1]));
                $colValue = trim($rowMatch[2]);

                if (self::isValidTag($tag)) {
                    if ($isStatusTable) {
                        $action = self::ACTION_AVAILABLE;
                        $isSubscribed = false;

                        if (preg_match('/\b(?:unsubscribed|removed)\b/i', $colValue)) {
                            $action = self::ACTION_UNSUBSCRIBE;
                            $isSubscribed = false;
                        } elseif (preg_match('/\b(?:already\s+subscribed|subscribed|rescanned\s+\d+)\b/i', $colValue)) {
                            $action = self::ACTION_SUBSCRIBE;
                            $isSubscribed = true;
                        }

                        $areas[] = [
                            'name'          => $tag,
                            'description'   => null,
                            'action'        => $action,
                            'is_subscribed' => $isSubscribed,
                        ];
                    } else {
                        $areas[] = [
                            'name'          => $tag,
                            'description'   => $colValue !== '' ? $colValue : null,
                            'action'        => self::ACTION_AVAILABLE,
                            'is_subscribed' => false,
                        ];
                    }
                }
                continue;
            }

            // Parse standard two-column line: TAG   Description
            if (preg_match('/^([A-Za-z0-9_\-\.]+)\s{3,}(.*)$/', $line, $rowMatch)) {
                $tag = strtoupper(trim($rowMatch[1]));
                $colValue = trim($rowMatch[2]);

                if (self::isValidTag($tag)) {
                    $areas[] = [
                        'name'          => $tag,
                        'description'   => $colValue !== '' ? $colValue : null,
                        'action'        => self::ACTION_AVAILABLE,
                        'is_subscribed' => false,
                    ];
                }
            }
        }

        return $headerFound ? $areas : null;
    }

    /**
     * Validate whether a string is syntactically a valid FTN echoarea/filearea tag.
     */
    public static function isValidTag(string $tag): bool
    {
        $upper = strtoupper(trim($tag));
        $len = strlen($upper);

        if ($len < 2 || $len > 60) {
            return false;
        }

        // Permitted characters: letters, digits, underscore, hyphen, period
        if (!preg_match('/^[A-Z0-9_\-\.]+$/', $upper)) {
            return false;
        }

        // Must contain at least one letter (prevents pure numbers or punctuation)
        if (!preg_match('/[A-Z]/', $upper)) {
            return false;
        }

        // Must not be a structural table token or command keyword
        $reserved = [
            'AREA', 'ECHOTAG', 'TAG', 'DESCRIPTION', 'DESC',
            'STATUS', 'MSGS', 'FILES', 'COMMAND', 'RESULT',
            'HELP', 'PASSWORD', 'ORIGIN', 'DEST'
        ];

        return !in_array($upper, $reserved, true);
    }

    /**
     * Deduplicate parsed areas by uppercase tag, giving precedence to subscriptions
     * and non-empty descriptions.
     *
     * @param array<int, array{name: string, description: ?string, action: string, is_subscribed: bool}> $areas
     * @return array<int, array{name: string, description: ?string, action: string, is_subscribed: bool}>
     */
    private function deduplicateAreas(array $areas): array
    {
        $map = [];

        foreach ($areas as $item) {
            $tag = strtoupper($item['name']);
            if (!isset($map[$tag])) {
                $map[$tag] = $item;
                continue;
            }

            // Precedence: subscribe > unsubscribe > available
            if ($item['action'] === self::ACTION_SUBSCRIBE) {
                $map[$tag]['action'] = self::ACTION_SUBSCRIBE;
                $map[$tag]['is_subscribed'] = true;
            } elseif ($item['action'] === self::ACTION_UNSUBSCRIBE && $map[$tag]['action'] !== self::ACTION_SUBSCRIBE) {
                $map[$tag]['action'] = self::ACTION_UNSUBSCRIBE;
                $map[$tag]['is_subscribed'] = false;
            }

            // Retain description if provided
            if (!empty($item['description']) && empty($map[$tag]['description'])) {
                $map[$tag]['description'] = $item['description'];
            }
        }

        return array_values($map);
    }
}
