@ECHO OFF
IF EXIST DOORWAY\DOORWAY.EXE GOTO REGISTERED
DOORWAY\DOORWAYU COM1 /g:on /a:on /m:100 /v:d^U /s:* /c:dos
GOTO END
:REGISTERED
DOORWAY\DOORWAY COM1 /o /g:on /a:on /m:100 /v:d^U /s:* /c:dos
:END
