[program:mrc_daemon]
command=php /var/www/html/scripts/mrc_daemon.php
autostart=true
autorestart=true
stdout_logfile=/var/www/html/data/logs/mrc_daemon.log
stdout_logfile_maxbytes=10485760
stderr_logfile=/var/www/html/data/logs/mrc_daemon_error.log
stderr_logfile_maxbytes=10485760
user=binkterm
directory=/var/www/html
